sudo: required
services:
  - docker

before_install:
  - docker build -t paulomedeiros88/fibonacci-app:dev -f ./app/Dockerfile.dev ./app

script:
  - docker run -e CI=true paulomedeiros88/fibonacci-app:dev npm test

after_success:
  - docker build -t paulomedeiros88/fibonacci-app ./app
  - docker build -t paulomedeiros88/fibonacci-nginx ./nginx
  - docker build -t paulomedeiros88/fibonacci-server ./server
  - docker build -t paulomedeiros88/fibonacci-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push paulomedeiros88/fibonacci-app
  - docker push paulomedeiros88/fibonacci-nginx
  - docker push paulomedeiros88/fibonacci-server
  - docker push paulomedeiros88/fibonacci-worker

deploy:
  provider: elasticbeanstalk
  region: sa-east-1
  app: awesome-fibonacci-calc
  env: AwesomeFibonacciCalc-env-1
  bucket_name: elasticbeanstalk-sa-east-1-669887589980
  bucket_path: fibonacci
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key:
    secure: $AWS_SECRET_ACCESS_KEY
