version: "3"
services:
  postgres:
    image: "postgres:12.1-alpine"
    environment:
      - POSTGRES_DB=fibonacci
      - POSTGRES_USER=fibonacci
      - POSTGRES_PASSWORD=fibonacci
  redis:
    image: "redis:5.0.7-alpine"
  api:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    image: "paulomedeiros/fibonacci-server:development"
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=fibonacci
      - POSTGRES_USER=fibonacci
      - POSTGRES_PASSWORD=fibonacci
    depends_on:
      - postgres
      - redis
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    image: "paulomedeiros/fibonacci-worker:development"
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
  app:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    image: "paulomedeiros/fibonacci-app:development"
    volumes:
      - /app/node_modules
      - ./app:/app
  nginx:
    image: "nginx:1.17.6-alpine"
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
